version: '3.8'

services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - "18888:18888"
    restart: unless-stopped

  Messaging:
    container_name: "Messaging"
    image: "docker.io/library/rabbitmq:4.0-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "gebhaLxSdDEeupIyPjW!Ym"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "Messaging"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  Redis:
    container_name: "Redis"
    image: "docker.io/library/redis:7.4"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "Redis"
    ports:
      - "6379:6379"
    restart: unless-stopped

  webapi:
    container_name: "altskuf-webapi"
    build:
      context: ./src/AltSKUF.WebApi  # Указываем папку с Dockerfile для AltSKUF.WebApi
      dockerfile: Dockerfile         # Указываем имя Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "AltSKUF.WebApi"
      ConnectionStrings__Messaging: "amqp://guest:gebhaLxSdDEeupIyPjW!Ym@Messaging:5672"
      ConnectionStrings__Redis: "Redis:6379"
    ports:
      - "10000:8080"
      - "10001:8443"
    restart: unless-stopped

  healthcheck:
    container_name: "healthcheck"
    build:
      context: ./repos/ALTSKUF.BACK.HealthCheck  # Указываем папку с Dockerfile для HealthCheck
      dockerfile: Dockerfile               # Указываем имя Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "HealthCheck"
      ConnectionStrings__Messaging: "amqp://guest:gebhaLxSdDEeupIyPjW!Ym@Messaging:5672"
    ports:
      - "10002:8080"
      - "10003:8443"
    restart: unless-stopped